title: "我的个人博客"           # 博客标题
description: "记录学习与成长"   # 博客描述
baseurl: ""                   # 保持为空
url: "https://你的用户名.github.io"  # 你的网站地址

# 主题设置（使用默认主题）
theme: jekyll-theme-cayman

# 构建设置
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

# 作者信息
author:
  name: "你的名字"
  email: "你的邮箱"
