# 博客站点设置
title: "我的博客"
description: "这是我的个人博客"
baseurl: "/blog" # 关键：必须设置为你的博客子目录路径
url: "https://你的用户名.github.io" # 你的网站主域名

# 构建设置
markdown: kramdown
theme: minima # 或你喜欢的主题

# 插件
plugins:
  - jekyll-feed
  - jekyll-paginate
