# 站点基本信息
title: "你的博客名称"
description: "一段吸引人的博客描述"
baseurl: "/blog"  # 关键：必须设置为你的博客子目录路径
url: "https://gervasw.github.io"  # 你的GitHub Pages主站地址

# 构建设置
markdown: kramdown
theme: minima  # 使用一个基础主题，确保兼容性

# 作者信息
author:
  name: "王维"
  bio: "这里写一段简短的自我介绍"

# 插件（确保GitHub Pages支持）
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 自定义设置（可选）
header_pages:
  - about.md