# 站点基本信息
title: "gervasw的博客"
description: "记录思考、学习与成长"
baseurl: "/blog"
url: "https://gervasw.github.io"

# 构建设置
markdown: kramdown
permalink: pretty

# 作者信息
author:
  name: "gervasw"
  bio: "欢迎来到我的数字花园，这里记录我的学习和思考"

# 插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 自定义设置
header_pages:
  - about.md