title: "你的博客名称"
description: "一段吸引人的博客描述"
baseurl: "/blog"
url: "https://你的用户名.github.io"

# 主题设置
theme: minima

# 构建设置
markdown: kramdown
permalink: pretty

# 作者信息
author:
  name: "你的名字"
  bio: "简短的个人介绍"
  avatar: "/blog/assets/images/avatar.jpg"
  location: "你的城市"
  
# 社交链接
social:
  github: 你的GitHub用户名
  twitter: 你的Twitter用户名
  email: 你的邮箱@example.com

# 自定义设置
header_pages:
  - about.md
  - archive.md

# 插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 外观设置
accent_color: "#3B82F6"  # 主色调
secondary_color: "#10B981" # 辅助色